# Generated by Django 5.0.4 on 2024-04-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_text', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_game.question')),
            ],
        ),
    ]
