# Generated by Django 5.0.4 on 2024-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_game', '0002_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
