# Generated by Django 5.0.4 on 2024-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_game', '0004_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique_for_date=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
    ]
