# Generated by Django 5.0.4 on 2024-05-20 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_game', '0006_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_text',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_game.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='result',
            name='passed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='result',
            name='r_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_game.student', verbose_name='id студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
